### ISSUE TITLE
Panic on packet scan

### ISSUE THREAD

**Issue by theonlydoo** [future-architect/vuls#131] opened 2016-07-12 13:52 UTC
```
goroutine 534 [running]:
panic(0xae3440, 0xc8206f89b0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/future-architect/vuls/scan.parallelSSHExec.func1(0xe7c660, 0xc820010c60, 0x7f19c96fb000, 0xc8201054a0)
	/go/src/github.com/future-architect/vuls/scan/sshutil.go:80 +0x37d
created by github.com/future-architect/vuls/scan.parallelSSHExec
	/go/src/github.com/future-architect/vuls/scan/sshutil.go:84 +0x166
```

I saw this on my latest scan, if it helps

**Comment by kotakanbe** [comment] 2016-07-12 14:01
Thanks for reporting.
please update Vuls, then try again.

**Comment by theonlydoo** [comment] 2016-07-12 14:05
on it

**Comment by kotakanbe** [comment] 2016-07-12 14:13
I want to get more information.
Please paste the output of running with --debug option?

**Comment by theonlydoo** [comment] 2016-07-12 14:33
it failed without debug, i run it again with debug mode

**Comment by theonlydoo** [comment] 2016-07-12 15:56
```
time="Jul 12 14:57:16" level=debug msg="Command: set -o pipefail; aptitude changelog docker-engine | grep '\\(urgency\\|CVE\\)'" 
time="Jul 12 14:57:16" level=debug msg="SSH executed. cmd: set -o pipefail; wget --tries=3 --timeout=1 --no-proxy -q -O - http://1.2.3.4/latest/meta-data/instance-id, err: <nil>, status: 4\nstdout: \n\nstderr: \n" 
panic: send on closed channel

goroutine 515 [running]:
panic(0xae3440, 0xc82060b320)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/future-architect/vuls/scan.parallelSSHExec.func1(0xe7c660, 0xc820258d20, 0x7f734519b9e8, 0xc820162000)
        /go/src/github.com/future-architect/vuls/scan/sshutil.go:80 +0x37d
created by github.com/future-architect/vuls/scan.parallelSSHExec
        /go/src/github.com/future-architect/vuls/scan/sshutil.go:84 +0x166
```
here you go

**Comment by kotakanbe** [comment] 2016-07-13 00:50
I can not reproduce this problem...

**Comment by kotakanbe** [comment] 2016-07-13 00:55
Probably, Snipped log is pasted. 

Please send me the entire log by email( kotakanbe@gmail.com ) or slack message if you like.
Vuls-slack ... https://vuls-github.slack.com/messages

You can join the slack team via this link.
https://docs.google.com/forms/d/e/1FAIpQLSfMyxCKV0C1ukTE0Mc9oyOHDI_2nbz4L75LAMj0D_A2vx_fMA/viewform?c=0&w=1

**Comment by kotakanbe** [comment] 2016-07-14 09:54
I understood the reason of this problem.
I am going to fix it.

**Comment by theonlydoo** [comment] 2016-07-14 14:16
okay! Thanks a lot! I didnt had time to go into more details on slack even though I cared to join, sorry.

**Comment by kotakanbe** [comment] 2016-07-19 04:48
This problem was fixed in #134 . 
Please try with latest revision.
Thanks for reporting!

**Comment by theonlydoo** [comment] 2016-07-19 07:38
All right, version will be in trial in a few hours

**Comment by kotakanbe** [comment] 2016-08-18 07:42
If you are still in trouble, reopen the issue.
Thanks.

**Closed by kotakanbe** 2016-08-18 07:42 UTC
Labels: bug
