### ISSUE TITLE
Report: failed to read from json (Docker)

### ISSUE THREAD

**Issue by xpfgsyb** [future-architect/vuls#294] opened 2017-01-15 00:54 UTC
Hi,
if I run the current Docker container with the **report** parameter I always get this message: `time="Jan 15 01:38:55" level=error msg="Failed to read from JSON: Stdin is invalid: "`. No other output is created and no mail is sent.

**Environment**
vuls v0.2.0 8e77937 (Docker-Image, Tag latest, Image ID af4a684f4a87)
Docker version 1.12.6, build 78d1802
Server: Debian 8.6
Command: `docker run --rm -v /home/service/vuls-data/ssh:/root/.ssh:ro -v /home/service/vuls-data/data/:/vuls -v /home/service/vuls-data/log/vuls/:/var/log/vuls -v /etc/localtime:/etc/localtime:ro vuls/vuls report -cvedb-path=/vuls/cve.sqlite3 -format-short-text -config=/vuls/config.toml -to-email -debug`

The results directory is located directly within the mapped data directory. Have I missed something at the update to 0.2 or is this a bug?

**Comment by kotakanbe** [comment] 2017-01-16 05:12
@xpfgsyb Thanks. I will check the issue.

**Comment by Klar** [comment] 2017-01-20 15:56
I've seen the same issue but on a normal ubuntu server. I run the report command via a bash script. It works when I run the script. But I get the same error message as above when I run it via crontab.

crontab -e
`56 14 * * 1-5 /home/username/vuls/run_vuls._report.sh`

cat /home/username/vuls/run_vuls_report.sh

`#!/bin/sh

/bin/vuls report -config=/home/username/vuls/config.toml -cvedb-path=/home/username/vuls/go-cve-dictionary/cve.sqlite3 -results-dir=/home/username/vuls/results/ -format-one-line-text -format-full-text -debug > /tmp/hello.txt`

* /tmp/hello.txt is empty after cronjob
* not empty after running with ./home/username/vuls/run_vuls._report.sh

**Comment by rinForIssue** [comment] 2017-01-23 07:34
I'm also suffering from the same issue since last wednesday.
Error occurs only when cron is executed. There is no problem with command execution.

> time="Jan19 17:01:01" level=error msg="Failed to read from JSON: Stdin is invalid:`

**Comment by kotakanbe** [comment] 2017-01-23 13:02
@xpfgsyb @rinForIssue 

The -it flag is required
```
docker run --rm -it ...
```

**Comment by kotakanbe** [comment] 2017-01-23 15:28
@Klar 
It was reproduced.
I am trying to solve this problem. see #299

**Comment by kotakanbe** [comment] 2017-01-23 16:14
@Klar 
Merged to master branch. Please try it out.

**Comment by rinForIssue** [comment] 2017-01-24 02:30
@kotakanbe 
Thanks!  Works Well with Update line on CentOS/RHEL6

**Comment by xpfgsyb** [comment] 2017-01-24 11:51
Thank you @kotakanbe, the -it flag did the trick :)

**Comment by Klar** [comment] 2017-01-25 15:39
@kotakanbe I tried it with the -pipe command but couldn't get it to work, did you test it, if so how does your script / crontab look?

thanks a lot

**Comment by kotakanbe** [comment] 2017-01-26 08:24
@Klar 
The -pipe option is not required for crontab.

**Comment by Klar** [comment] 2017-01-26 09:07
@kotakanbe 
it's working now, thanks a lot! :+1:

**Closed** 2017-01-26 09:18 UTC
