### ISSUE TITLE
unable to scan  remote host

### ISSUE THREAD

**Issue by danie-dejager** [future-architect/vuls#2083] opened 2024-12-11 10:29 UTC
I cannot initiate a remote scan using the tutorial. I started with https://vuls.io/docs/en/install-with-vulsctl.html
My config is:
```
[servers]
[servers.centos7]
host               = "192.168.88.252"
user               = "root"
port               = "22"
keyPath            = "/root/.ssh/id_rsa"
scanMode           = ["fast"]
```
I run:
`docker run --rm -it    -v ~/.ssh:/root/.ssh:ro     -v $PWD:/vuls     -v $PWD/vuls-log:/var/log/vuls     vuls/vuls configtest     -config=./config.toml`
or
`./config-test.sh`
The error I get is:
```
[Dec 11 10:44:48]  INFO [localhost] vuls-v0.28.0-build-20241208_083945_703ba66
[Dec 11 10:44:48]  INFO [localhost] Validating config...
[Dec 11 10:44:48]  INFO [localhost] Detecting Server/Container OS... 
[Dec 11 10:44:48]  INFO [localhost] Detecting OS of servers... 
[Dec 11 10:44:48] ERROR [localhost] (1/1) Failed: centos7, err: [Failed to print SSH configuration. err:
    github.com/future-architect/vuls/scanner.validateSSHConfig
        /go/src/github.com/future-architect/vuls/scanner/scanner.go:413
  - exit status 255]
[Dec 11 10:44:48]  INFO [localhost] Detecting OS of containers... 

```

I can ssh to the target host using the id_rsa key. Not sure what I'm missing, the error is not super helpful.

**Comment by MaineK00n** [comment] 2024-12-11 12:26
Can you provide the execution log with the `-debug` option?
```console
$ docker run --rm -it -v ~/.ssh:/root/.ssh:ro -v $PWD:/vuls -v $PWD/vuls-log:/var/log/vuls vuls/vuls configtest -config=./config.toml -debug
```

**Comment by danie-dejager** [comment] 2024-12-11 12:37
pwd:
`/data_vol/projects/vulsctl/docker`
```
docker run --rm -it -v ~/.ssh:/root/.ssh:ro -v $PWD:/vuls -v $PWD/vuls-log:/var/log/vuls vuls/vuls configtest -config=./config.toml -debug
[Dec 11 12:36:46]  INFO [localhost] vuls-v0.28.0-build-20241208_083945_703ba66
[Dec 11 12:36:46]  INFO [localhost] Validating config...
[Dec 11 12:36:46]  INFO [localhost] Detecting Server/Container OS... 
[Dec 11 12:36:46]  INFO [localhost] Detecting OS of servers... 
[Dec 11 12:36:46] DEBUG [localhost] Validating SSH Settings for Server:centos7 ...
[Dec 11 12:36:46] DEBUG [localhost] Executing... /usr/bin/ssh -G -i /root/.ssh/id_rsa -p 22 -l danie.dejager 192.168.88.252
[Dec 11 12:36:46] ERROR [localhost] (1/1) Failed: centos7, err: [Failed to print SSH configuration. err:
    github.com/future-architect/vuls/scanner.validateSSHConfig
        /go/src/github.com/future-architect/vuls/scanner/scanner.go:413
  - exit status 255]
[Dec 11 12:36:46]  INFO [localhost] Detecting OS of containers... 
[Dec 11 12:36:46]  INFO [localhost] Checking Scan Modes...
[Dec 11 12:36:46]  INFO [localhost] Checking dependencies...
[Dec 11 12:36:46]  INFO [localhost] Checking sudo settings...
[Dec 11 12:36:46]  INFO [localhost] It can be scanned with fast scan mode even if warn or err messages are displayed due to lack of dependent packages or sudo settings in fast-root or deep scan mode
[Dec 11 12:36:46] ERROR [localhost] Failed to configtest: No scannable servers:
    github.com/future-architect/vuls/scanner.Scanner.Configtest
        /go/src/github.com/future-architect/vuls/scanner/scanner.go:137
```

**Comment by MaineK00n** [comment] 2024-12-11 12:52
Try running the following command from within the container
```console
/usr/bin/ssh -G -i /root/.ssh/id_rsa -p 22 -l danie.dejager 192.168.88.252
```

**Comment by danie-dejager** [comment] 2024-12-11 13:04
I get a permissions issue on the config file from my /home/danie.dejager/.ssh/config mounted to the container:
``` 
Bad owner or permissions on /root/.ssh/config
/vuls # ls -l /root/.ssh/config
-rw-r--r--    1 1001     1001          2877 Oct 15 11:44 /root/.ssh/config
```

**Comment by MaineK00n** [comment] 2024-12-11 13:06
Please fix the permissions and try again.

**Comment by danie-dejager** [comment] 2024-12-11 13:06
chown: /root/.ssh/config: Read-only file system

**Comment by MaineK00n** [comment] 2024-12-11 13:10
It seems that mounting with ro is the cause. `-v ~/.ssh:/root/.ssh:ro`

**Comment by danie-dejager** [comment] 2024-12-11 13:15
I mounted with `rw` but it still complains about permissions. I was able to ssh to the target from within the docker when i moved my ssh config out of the way.
```
/vuls # /usr/bin/ssh -G -i /root/.ssh/id_rsa -p 22 -l danie.dejager 192.168.88.252
```
now the shell script also works.
How should I configure if I wanted to use my config file? I tried the toml with and without `sshConfigPath`

**Comment by MaineK00n** [comment] 2024-12-11 13:23
Anyway, I'm glad that it seems to have been successful.
If you have an ssh config file you want to load, enter the path to it in `sshConfigPath`.
Then, it will be interpreted internally as follows:
```console
ssh -F <sshConfigPath>
```

**Comment by danie-dejager** [comment] 2024-12-11 13:32
Maybe somethin's changed since the last the `sshConfigPath` was written. Looking at `/root/.ssh` from inside the cotnainer I see that all the files in there are owned by `1001:1001` and if I mount the container using `rw` and chown `root:root` the config file then SSH works. It may be the later versions of openssh requires the users to own the config they use.

**Closed** 2024-12-11 14:05 UTC
Labels: question
