### ISSUE TITLE
The OVAL name of the running kernel image  is not found

### ISSUE THREAD

**Issue by thinksabin** [future-architect/vuls#845] opened 2019-06-17 07:44 UTC
# What did you do? (required. The issue will be **closed** when not provided.)
vuls scan <nodename>
vuls tui

# What did you expect to happen?

display vuls tui

# What happened instead?

[Jun 17 07:38:58] DEBUG [localhost] Check whether oval fetched: ubuntu 16.04
[Jun 17 07:38:58]  INFO [localhost] OVAL is fresh: ubuntu 16.04 
[Jun 17 07:38:58]  WARN [localhost] The OVAL name of the running kernel image  is not found. So vulns of linux-image-generic wll be detected. server: logpoint651
[Jun 17 07:38:58] ERROR [localhost] Failed to fill with OVAL: Failed to get ubuntu OVAL info by package: oval.request{packName:"linux-meta-hwe", versionRelease:"4.15.0.32.54", newVersionRelease:"", arch:"", binaryPackNames:[]string{"linux-generic-hwe-16.04", "linux-headers-generic-hwe-16.04", "linux-image-generic-hwe-16.04"}, isSrcPack:true}, err: too many SQL variables

* Current Output

Please re-run the command using ```-debug``` and provide the output below.

# Steps to reproduce the behaviour

# Configuration (**MUST** fill this out):

* Go version (`go version`):
go version go1.12 linux/amd64

* Go environment (`go env`):
ubuntu@SecurityVuls:~$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ubuntu/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ubuntu/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build144363051=/tmp/go-build -gno-record-gcc-switches"

* Vuls environment:

Hash : ____

To check the commit hash of HEAD
$ vuls -v
vuls v0.7.0 build-20190615_143533_8c3b305

or

$ cd $GOPATH/src/github.com/future-architect/vuls 
$ git rev-parse --short HEAD 

* config.toml:

* command:

**Comment by kotakanbe** [comment] 2019-06-17 07:47
@thinksabin 

Would you please send me the JSON file via slack DM?
(You can join the vuls-github slack team via https://docs.google.com/forms/d/e/1FAIpQLSfMyxCKV0C1ukTE0Mc9oyOHDI_2nbz4L75LAMj0D_A2vx_fMA/viewform?c=0&w=1)

I want to reproduce the issue.

**Comment by thinksabin** [comment] 2019-06-17 07:51
sure, just a minute.

**Comment by patrickbaber** [comment] 2019-07-02 08:59
I had the same problem running `vuls report` with version `v0.8.2`. Is there a workaround like setting an env var to increase the limit? This is the output of the command:

```
[Jul  2 08:52:51]  INFO [localhost] [Reboot Required] example-server: 0 CVEs are detected with Library
[Jul  2 08:52:51]  INFO [localhost] OVAL is fresh: ubuntu 16.04
[Jul  2 08:52:51]  WARN [localhost] The OVAL name of the running kernel image  is not found. So vulns of linux-image-generic wll be detected. server: example-server
[Jul  2 08:52:51] ERROR [localhost] Failed to fill with OVAL:
    github.com/future-architect/vuls/report.FillCveInfo
        /go/src/github.com/future-architect/vuls/report/report.go:178
  - Failed to get ubuntu OVAL info by package: oval.request{packName:"linux-meta-hwe", versionRelease:"4.15.0.54.75", newVersionRelease:"", arch:"", binaryPackNames:[]string{"linux-headers-generic-hwe-16.04", "linux-image-generic-hwe-16.04"}, isSrcPack:true}, err:
    github.com/future-architect/vuls/oval.getDefsByPackNameFromOvalDB
        /go/src/github.com/future-architect/vuls/oval/util.go:243
  - too many SQL variables
```

The kernel of the scan target is `Linux example-server 4.15.0-52-generic #56~16.04.1-Ubuntu SMP Thu Jun 6 12:03:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`.

**Comment by thinksabin** [comment] 2019-07-09 05:53
@patrickbaber  @kotakanbe will be looking into it as per his message in slack channel. With me , the issue was in the using the HWE kernel version of linux. For normal kernel shipped with the ubuntu, vuls report is working fine.

**Comment by patrickbaber** [comment] 2019-08-05 09:37
With version `v0.8.5 build-20190730_085002_4326bef` I still get the error and I can't find a suitable replacement for the Kernel. We are using the official Debian Kernel `linux-image-4.15.0-55-generic`. Because of the fact that the whole report fails, I have to disable the scan for this specific machine, to get notifications about the other machines in the config.

**Comment by kotakanbe** [comment] 2020-04-28 07:17
Maybe fixed in https://github.com/future-architect/vuls/pull/958

**Closed by kotakanbe** 2020-04-28 07:17 UTC
Labels: bug

**Comment by KingXS** [comment] 2020-12-29 09:50
[Dec 29 17:32:14]  WARN [localhost] The OVAL name of the running kernel image {Release:3.19.0-25-generic Version: RebootRequired:false} is not found. So vulns of `linux` wll be detected. server: ubuntu
 how to solve it
