### ISSUE TITLE
ERRO[0000]

### ISSUE THREAD

**Issue by duckmak14** [future-architect/vuls#964] opened 2020-04-23 10:40 UTC
i have just used vuls. i do not know where i'm wrong. i installed on ubuntu 18.04. 
scan eror: 
ERRO[0000] httpProxy:  does not validate as url;Slack.HookURL:  does not validate as url;EMail.SMTPPort:  does not validate as port;HTTP.URL:  does not validate as url;Syslog.Host:  does not validate as host;Syslog.Port:  does not validate as port
file config.toml: 

[cveDict]
type = "sqlite3"
SQLite3Path = "/usr/share/vuls-data/cve.sqlite3"

[ovalDict]
type = "sqlite3"
SQLite3Path = "/usr/share/vuls-data/oval.sqlite3"

[gost]
type = "sqlite3"
SQLite3Path = "/usr/share/vuls-data/gost.sqlite3"

[servers]

[servers.localhost]
host = "127.0.0.1"
port = "22"
user= "root"
scanMode = [ "fast" ]

help me, please !

**Comment by alexandruavadanii** [comment] 2020-04-23 17:17
Looks like a duplicate of https://github.com/future-architect/vuls/issues/962
You should try rebuilding vuls from the latest master commit.

**Closed** 2020-04-27 05:48 UTC
Labels: question
